// Code generated by MockGen. DO NOT EDIT.
// Source: weather.go
//
// Generated by this command:
//
//	mockgen -source weather.go -destination mock_weather.go -package domain
//

// Package domain is a generated GoMock package.
package domain

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWeatherClient is a mock of WeatherClient interface.
type MockWeatherClient struct {
	ctrl     *gomock.Controller
	recorder *MockWeatherClientMockRecorder
}

// MockWeatherClientMockRecorder is the mock recorder for MockWeatherClient.
type MockWeatherClientMockRecorder struct {
	mock *MockWeatherClient
}

// NewMockWeatherClient creates a new mock instance.
func NewMockWeatherClient(ctrl *gomock.Controller) *MockWeatherClient {
	mock := &MockWeatherClient{ctrl: ctrl}
	mock.recorder = &MockWeatherClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWeatherClient) EXPECT() *MockWeatherClientMockRecorder {
	return m.recorder
}

// FetchWeatherByCity mocks base method.
func (m *MockWeatherClient) FetchWeatherByCity(ctx context.Context, city City) (*Weather, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchWeatherByCity", ctx, city)
	ret0, _ := ret[0].(*Weather)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchWeatherByCity indicates an expected call of FetchWeatherByCity.
func (mr *MockWeatherClientMockRecorder) FetchWeatherByCity(ctx, city any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchWeatherByCity", reflect.TypeOf((*MockWeatherClient)(nil).FetchWeatherByCity), ctx, city)
}
